<h1 style="background-color: <?= $this->getData('background_color') ?>;">Layout XML: Loading & Rendering</h1>
<h2>3.1. Add a default.xml layout file to the Training_Render module.</h2>
<ol>
    <li>Reference the content.top container.</li>
    <li>Add a Magento\Framework\View\Element\Template block with a custom template.</li>
    <li>Create your custom template</li>
    <li>Check that the template content is visible on every page.</li>
</ol>